sonar.projectKey=aula-pratica-9
sonar.projectName=Aula Pratica 9
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=bin
sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.password=wigbeGAP302!)